# Generated by Django 4.1.6 on 2023-03-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='content/avatars'),
        ),
    ]
