# Generated by Django 4.1.6 on 2023-03-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
        ('files', '0002_file_book_file_description'),
        ('books', '0004_remove_book_file_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='files.file')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_file', to='visitors.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='CommentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_book', to='visitors.visitor')),
            ],
        ),
    ]
