# Generated by Django 4.1.6 on 2023-03-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbook',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentfile',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
