# Generated by Django 4.1.6 on 2023-03-21 00:59

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_episode'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.Page.upload_page),
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='files.file'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.Page.upload_page),
        ),
    ]
