# Generated by Django 4.1.6 on 2023-03-20 12:05

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_storage_name'),
        ('files', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='storage_name',
            field=models.CharField(default='empty', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='books.book'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.File.upload_episode),
        ),
        migrations.AlterField(
            model_name='file',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to=files.models.File.upload_episode),
        ),
    ]
