# Generated by Django 4.1.6 on 2023-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_storage_name_alter_file_book_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='episode',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
