# Generated by Django 4.1.6 on 2023-02-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_file_alter_book_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
    ]
