# Generated by Django 4.1.6 on 2023-03-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUpcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='books')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
