# Generated by Django 4.1.6 on 2023-03-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
