# Generated by Django 4.1.6 on 2023-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_image_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='storage_name',
            field=models.CharField(default='empty', max_length=256, unique=True),
        ),
    ]
